### ISSUE TITLE
 GSAP Text Animations on Homepage

### ISSUE THREAD

**Issue by priyashuu** [beRajeevKumar/Frontend_Mentor#10]
**Objective**: I propose enhancing the homepage with text animations using GSAP (GreenSock Animation Platform) to improve user engagement and make the interface more dynamic.

**Details**:
- Animate heading and subheading text on page load.
- Include subtle fade-in or slide-in animations for improved visual appeal.
- Ensure animations are responsive and do not affect performance on lower-end devices.
- Will add comments to code to ensure clarity for future contributors.

Please assign this issue to me, as I would love to work on it. I am also a contributor in GGSOCExt 24 , hacktoberfest.

Looking forward to your feedback!

**Comment by beRajeevKumar** [comment]
@priyashuu, share your potential design solution. what will your inspiration for the design be before implementation?
What does the design of the page look like? 
If you want to design, then you can design your solution in the Figma link here👇
https://www.figma.com/design/Gpp9lztaz36xu9nuGt7FBE/Frontend-Mentor?node-id=0-1&t=vJh3LEbs3Fw4ZmwL-1

for further discussion or any doubt, Join the discord server here: 
https://discord.gg/eXrQqgRX

**Comment by beRajeevKumar** [comment]
@priyashuu, if you want to work on this issue, then go for it.
If you have any doubts, then feel free to ask here in our discord server.
https://discord.gg/4rMUncEV

**Comment by priyashuu** [comment]
ok sir
