### ISSUE TITLE
Missing components

### ISSUE THREAD

**Issue by Prashant1659** [beRajeevKumar/Frontend_Mentor#11]
There is no footer, navigation bar, logo and name of website. Website is also too blocky. We can add a form page so that user can put their review or they can request any particular project that we can add on website. Kindly assign this issue to me labels gssoc, hackoberfest

**Comment by beRajeevKumar** [comment]
Can you share your inspired design solution and what the project will look like after implementation?
If you are ready to craft its design, then let's join the Figma link and work together on its design. 
Here is the link:
https://www.figma.com/design/Gpp9lztaz36xu9nuGt7FBE/Frontend-Mentor?node-id=0-1&t=vJh3LEbs3Fw4ZmwL-1
If you have any doubts or discussion, join the discord server for better communication.
https://discord.gg/eXrQqgRX

**Comment by lavanyabandari** [comment]
A footer  plays a crucial role in enhancing user experience, providing essential information, and supporting site navigation. A well-designed footer can lead to increased engagement, improved usability, and higher conversion rates. 
Here are some key importances of having a well-designed footer:
1. Navigation

    Links to Important Pages: The footer can contain links to key sections of the website, such as About Us, Contact, Privacy Policy, Terms of Service, and FAQs. This aids users in finding important information quickly, especially if they have scrolled down the page.

2. Contact Information

    Accessibility: Including contact details (email, phone number, physical address) in the footer ensures that users can easily reach out for support or inquiries without searching the site.

3. Social Media Links

    Engagement: Footers are often the best place to include links to social media profiles. This allows users to connect with the brand or organization on various platforms, fostering community engagement.


 please assign me the project “Add Links to Social Media Icons in Footer.” I’m eager to contribute!

**Comment by lavanyabandari** [comment]
please assign me the project “Add Links to Social Media Icons in Footer.” I’m eager to contribute!
