### ISSUE TITLE
Create Login/Signup Authentication Component

### ISSUE THREAD

**Issue by saras-69** [beRajeevKumar/Frontend_Mentor#12]
Description:
I would like to implement a login and signup authentication component for the application. This component will allow users to register and log in securely.

Proposed Solution:

Design a user-friendly interface for the login and signup forms.
Implement form validation to ensure all required fields are completed correctly.
Integrate authentication with a backend service (e.g., JWT, OAuth).
Handle error messages for failed login attempts and validation issues.
Include features for password recovery and account verification.
Benefits:

Provides users with a secure way to access their accounts.
Enhances overall user experience by allowing personalized features.

"Please assign this issue to me so that I can work on it."

**Comment by beRajeevKumar** [comment]
Can you share your inspired design solution and what the project will look like after implementation?
If you are ready to craft its design, then let's join the Figma link and work together on its design.
Here is the link:
https://www.figma.com/design/Gpp9lztaz36xu9nuGt7FBE/Frontend-Mentor?node-id=0-1&t=vJh3LEbs3Fw4ZmwL-1
If you have any doubts or discussion, join the discord server for better communication.
https://discord.gg/eXrQqgRX

**Comment by saras-69** [comment]
"Hey! I'm not very experienced with UI/UX design or using Figma, but I can definitely help by providing a fully responsive login and signup page with proper authentication. Let me know if that works, and I'd be happy to contribute to the project in that way!"

**Comment by saras-69** [comment]
@beRajeevKumar "Hey! I'm not very experienced with UI/UX design or using Figma, but I can definitely help by providing a fully responsive login and signup page with proper authentication. Let me know if that works, and I'd be happy to contribute to the project in that way!" 
i drop on ss
![Screenshot 2024-10-02 055055](https://github.com/user-attachments/assets/bfae09ca-69f6-4b62-b151-8390f70d9ee0)

**Comment by beRajeevKumar** [comment]
Nice go for it 🚀

**Comment by saras-69** [comment]
@beRajeevKumar  could you please look into this https://github.com/beRajeevKumar/Frontend_Mentor/pull/248#issuecomment-2405672419
