### ISSUE TITLE
Error in Readme file

### ISSUE THREAD

**Issue by Prashant1659** [beRajeevKumar/Frontend_Mentor#13]
There are 26 projects assigned in readme file but 21 are present on website page. From 1-5 projects are not present. The first project on website "Community Card" is also not mentioned in Readme file.

**Comment by jjf2009** [comment]
Kindly assign me this issue

**Comment by jjf2009** [comment]
Kindly assign me this issue

**Comment by rohitsharma2610** [comment]
can you please assign it to me i want to work on this.
