### ISSUE TITLE
add a button to scroll at the top

### ISSUE THREAD

**Issue by ShrishtiSingh26** [beRajeevKumar/Frontend_Mentor#14]
I wish to add a button at the bottom which allows the user to scroll back at the top.

Please assign me this issue

**Comment by beRajeevKumar** [comment]
It's a good idea to have a `scroll back to top` button on a web page, but first of all, We are working on project design.
so join this link figma link: 
https://www.figma.com/design/Gpp9lztaz36xu9nuGt7FBE/Frontend-Mentor?node-id=0-1&t=vJh3LEbs3Fw4ZmwL-1
for further discussion or doubts join the discord server here.
https://discord.gg/eXrQqgRX

**Comment by Mohith1490** [comment]
Hey @beRajeevKumar can i work on this issue 
for Hacktoberfest

**Comment by beRajeevKumar** [comment]
Hey @Mohith1490, Please read the above comment.

**Comment by ShrishtiSingh26** [comment]
@beRajeevKumar I have created a PR and closed the issue #14
Thank you!
