### ISSUE TITLE
 Implement Advanced Contact Form with Accessibility, Responsiveness, Real-time Validation, and Enhanced User Experience Description:

### ISSUE THREAD

**Issue by Titus210** [beRajeevKumar/Frontend_Mentor#147]
## Issue Overview:
I would like to contribute by implementing an advanced version of the contact form that aligns closely with the provided design specifications while enhancing accessibility, responsiveness, and user experience. This implementation will include dynamic error handling, screen reader support, keyboard navigation, and real-time validation, along with an option to save draft inputs locally.

## Proposed Solution:
The solution is from one of the frontend mentor challenges [Contact Form](https://www.frontendmentor.io/challenges/contact-form--G-hYlqKJj)
The project images are below

![desktop-design](https://github.com/user-attachments/assets/f7c24963-2ed6-49e4-a4ae-ffe1ce1486a3)

The solution will cover the following aspects:

**1. Accessibility Features:**

- Use aria-live regions to announce error messages and success messages for screen reader users.
- Implement aria-labels and aria-describedby attributes for form inputs to ensure clear instructions and context for screen readers.
- Manage focus state during validation errors and form submission, providing appropriate feedback for keyboard-only users.

**2. Form Validation:**

- Implement client-side form validation with real-time feedback for all input fields, including:
- Required fields check for "Name", "Email", and "Message".
- Real-time email validation using a regular expression pattern.
- Display error messages dynamically next to invalid input fields with smooth animations.

**3. Enhanced User Experience:**

- Create animated transitions for displaying and hiding error messages, using subtle fade-in and slide-in effects.
- Display a custom success toast message upon successful form submission, including:
- Dismiss button for manual closing.
- Auto-hide feature to remove the toast after 5 seconds.

![focus-and-active-state](https://github.com/user-attachments/assets/ea62af70-2186-4403-adce-7734968fb77a)
![hover-state](https://github.com/user-attachments/assets/f5f422b6-66b2-40e0-8765-40c147e1ebca)

**4. Responsive Design:**

- Implement responsive styling to ensure the form adapts to different screen sizes, providing an optimal experience on mobile, tablet, and desktop devices.
- Include media queries to adjust form layout, padding, and touch target sizes for accessibility on smaller screens.

![mobile-design](https://github.com/user-attachments/assets/8f948b19-4c2a-4e8c-a3af-1cd85ac577b6)

**5. Save Draft Feature:**

- Allow users to save form input data locally using local storage, so they don’t lose progress if the page is accidentally refreshed or closed.
- Automatically load saved draft data when the user revisits the page, pre-filling the form with their previous inputs.
- Include a “Clear Draft” button to reset the form and clear local storage data if the user wishes to start over.

**6. Keyboard Navigation and Focus Management:**

- Ensure the form can be completed using only the keyboard by managing focus for each form element.
- Shift focus to the first invalid input upon form validation errors.
- Shift focus to the success toast message upon successful submission for better user feedback.

**7. Expected Outcome:**
The enhanced contact form will provide a smooth and accessible experience for all users, including those using screen readers or keyboard-only navigation. It will be responsive across various device sizes, offer real-time feedback during form input, and ensure no data is lost with the Save Draft feature. Additionally, subtle animations and dynamic error messages will contribute to an overall improved user experience.

@beRajeevKumar Let me know if I can proceed with this implementation or if there are additional guidelines or features, you’d like to include like what to name the project folder i.e 25-Contact-form. Thank you!

**Comment by beRajeevKumar** [comment]
Go for it man 🚀

**Comment by Titus210** [comment]
Sure...I will be updating the repo soon😊💯.
