### ISSUE TITLE
Adding GSAP animations in ALL Cards  ......

### ISSUE THREAD

**Issue by devxMani** [beRajeevKumar/Frontend_Mentor#15]
can you assign this issue to me and add Gsoc Ext and Hacktoberfest labels to it...

**Comment by beRajeevKumar** [comment]
Can you share your inspired design solution and what the project will look like after implementation?
If you are ready to craft its design, then let's join the Figma link and work together on its design.
Here is the link:
https://www.figma.com/design/Gpp9lztaz36xu9nuGt7FBE/Frontend-Mentor?node-id=0-1&t=vJh3LEbs3Fw4ZmwL-1
If you have any doubts or discussion, join the discord server for better communication.
https://discord.gg/eXrQqgRX

**Comment by shubham7522** [comment]
if this issue is open can i work on this?
