### ISSUE TITLE
Enhancing Overall Design: Improving Home Visibility to Elevate User Experience and Add Footer section

### ISSUE THREAD

**Issue by Mayursoni1518** [beRajeevKumar/Frontend_Mentor#18]
Your website currently appears too basic and requires immediate improvements to enhance its overall functionality and aesthetic appeal. One critical area that is missing is the footer section, which is essential for providing users with quick access to important information and resources.

Additionally, the lack of clear and visually appealing icons further detracts from the user experience. Icons play a vital role in guiding users, enhancing navigation, and making the interface more engaging. By incorporating a well-designed footer and improving icon visibility, we can significantly elevate the user experience, build trust, and encourage user interaction with the website.
Please Assign this issue to me under Gssoc extd'24

**Comment by beRajeevKumar** [comment]
Are you a UX/UI Designer?

**Comment by beRajeevKumar** [comment]
If you are ready to contribute to its design, then join this Figma design and build the project design here.
https://www.figma.com/design/Gpp9lztaz36xu9nuGt7FBE/Frontend-Mentor?node-id=0-1&t=EsBgxOX2KNk25lYb-1
First, build an overall design for the project, and then we will code it.
For further discussions and doubts ask here on the discord server.
https://discord.gg/4rMUncEV

**Comment by Mayursoni1518** [comment]
I am not UI /UX designer I am web developer can help you to improve your
overall design of the website

**Comment by beRajeevKumar** [comment]
Hello @anuragbansall, go for it🚀

**Comment by anuragbansall** [comment]
Thanks @beRajeevKumar 

I noticed you mentioned a Figma design earlier. It would be great if you could provide access to view it.

**Comment by beRajeevKumar** [comment]
Ok send me the request
