### ISSUE TITLE
Create a CONTRIBUTING.md Guidelines

### ISSUE THREAD

**Issue by Amulya-B28** [beRajeevKumar/Frontend_Mentor#181]
I would like to add this because this file is a crucial document in open-source repositories, providing clear guidelines and instructions for anyone interested in contributing to the project. It outlines how contributors can get involved, the contribution process, and the repository's coding standards and rules. Please assign me this task.

**Comment by beRajeevKumar** [comment]
go for it🚀

**Comment by beRajeevKumar** [comment]
if you have any doubts, then ask here on the discord server.
https://discord.gg/cWDQjdhd
