### ISSUE TITLE
Enhance title of website

### ISSUE THREAD

**Issue by himanshu-sheetlani** [beRajeevKumar/Frontend_Mentor#19]
The title of the website just says "Frontend Mentor Challenges" which can be enhanced with logo and styling.

**Comment by beRajeevKumar** [comment]
Yeah, of course. Just share with me your potential design solution once. Show any example design of how It will look after implementation.
Then I will assign it to you.
If you have any other doubts, then ask here in the discord server to resolve the issues fast.
https://discord.gg/4rMUncEV

**Comment by Ashmita-15** [comment]
I can improve the logo of this website as currently the logo looks too simple. Please assign this to me:)
