### ISSUE TITLE
enhancement navbar

### ISSUE THREAD

**Issue by sanayamahajan-23** [beRajeevKumar/Frontend_Mentor#2]
enhance the navbar design

**Comment by chaheti89** [comment]
Can I work on this issue?

**Comment by shraddhabaghel** [comment]
please assign me this issue

**Comment by Abhiraj-Sardar** [comment]
can you assign me this issue?

**Comment by sanayamahajan-23** [comment]
@beRajeevKumar please specify have you assigned me this issue

**Comment by beRajeevKumar** [comment]
@sanayamahajan-23, Are you working on this issue or not?

**Comment by sanayamahajan-23** [comment]
Yes
