### ISSUE TITLE
Bug: "06-product-preview" project mobile version image is not correct

### ISSUE THREAD

**Issue by beRajeevKumar** [beRajeevKumar/Frontend_Mentor#27]
Mobile responsive design is not correct, use the `<picture>` tag and choose the two images for the different breakpoints.
For desktop design, use "image-product-desktop.jpg" in the images folder.
For mobile design, use "image-product-mobile.jpg" in the images folder.

**Comment by jjf2009** [comment]
Assign me this issue

**Comment by beRajeevKumar** [comment]
@jjf2009, Do it 🚀
