### ISSUE TITLE
Making it interactive for Users

### ISSUE THREAD

**Issue by Bhum-ika** [beRajeevKumar/Frontend_Mentor#3]
We can allow multiple users to log in to your website. If specific users have completed a project, they can upload their code for that project. This will help other users who are facing challenges in development to seek assistance. This approach will reduce the number of users giving up due to lack of available solutions.

I can use firebase for signing up and logging in and other functionalities can be implemented easily.

Kindly add gssoc24ext and hactoberfest tags in it

**Comment by chaheti89** [comment]
Can I be assigned to this issue?

**Comment by beRajeevKumar** [comment]
First, we have to work on its design

**Comment by beRajeevKumar** [comment]
@Bhum-ika, Do you want to work on this issue?  if yes, then go for it.
If you have any doubts, then join our discord server here.
https://discord.gg/4rMUncEV

**Comment by Bhum-ika** [comment]
Sure

**Comment by Kedarnath-Rothe** [comment]
Please Assign this issue to me under hactoberfest label
