### ISSUE TITLE
[BUG] Login Page Not Found - 404 Error on Click, Create login page 

### ISSUE THREAD

**Issue by Ankul8471** [beRajeevKumar/Frontend_Mentor#338]
### Description

When clicking on the "Login" page, a 404 error ("Page Not Found") is displayed instead of redirecting to the actual login form. The link seems broken or the login page has not been set up properly.

To fix this issue:

Investigate whether the URL routing for the login page is correctly configured.
Create or link the login page to ensure users can access the form without encountering the 404 error.
Ensure proper redirection after a user clicks on "Login" to avoid broken links.
Expected Result: When the "Login" button is clicked, users should be taken to a functional login form instead of encountering a 404 error.

### Screenshots

![1111](https://github.com/user-attachments/assets/d28f56fc-b77a-4e4f-b4b8-483fcf2548b8)

### Any additional information?

The issue appears when attempting to access the login page via the navigation menu.
The platform is hosted on Netlify, as indicated by the 404 error page template.
Ensure that the login page exists in the codebase and is correctly linked in the navigation.
Check the deployment settings or routes configuration (such as in netlify.toml or other routing files) to ensure the login page path is properly handled.
Test the fix locally before deployment to confirm that the login page loads as expected without errors.
Including this will provide more context to developers working on the issue. Let me know if you'd like to add more details!

### What browser are you seeing the problem on?

Chrome

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/beRajeevKumar/Frontend_Mentor/blob/main/Code_Of_Conduct.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by Ankul8471** [comment]
@beRajeevKumar  hello sir i would like to work on it please assign me

**Comment by beRajeevKumar** [comment]
Go for it

**Comment by Jyotish2002** [comment]
@beRajeevKumar Sir, I would like to request the opportunity to build a login and signup page for our project, with the option to log in using GitHub, LinkedIn, and Google. I will also ensure the page is fully responsive and incorporates an attractive, animated design to enhance user experience.
I am confident that I can complete this task within a day, and I am eager to contribute to the project. I would be incredibly grateful if you could assign me this task. I promise to give my best effort and deliver high-quality work.
