### ISSUE TITLE
Adding hover effects

### ISSUE THREAD

**Issue by bheemajayashreee** [beRajeevKumar/Frontend_Mentor#40]
Upon hovering on the card there should be someon-hover effect
![image](https://github.com/user-attachments/assets/005c8b82-472b-4db8-af39-5509e3df05ab)
There is no effect upon hovering

**Comment by Gayatri-Chaudhary** [comment]
I would like to work on this issue. Please assign it to me.

**Comment by anubhab1001** [comment]
@beRajeevKumar please assign me
