### ISSUE TITLE
[Feat]Add responsive restaurant website (Zaika Palace)

### ISSUE THREAD

**Issue by amanver45** [beRajeevKumar/Frontend_Mentor#414]
### Description

Implement a responsive design for the restaurant website, ensuring it adapts seamlessly across various devices including mobile, tablet, and desktop. The design should prioritize user experience and easy navigation, with menus, booking options, and other essential features accessible on all screen sizes.

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/beRajeevKumar/Frontend_Mentor/blob/main/Code_Of_Conduct.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by beRajeevKumar** [comment]
Gp for it
