### ISSUE TITLE
[BUG] Frontend Mentor moving navbar not visible

### ISSUE THREAD

**Issue by saumyayadav25** [beRajeevKumar/Frontend_Mentor#415]
### Description

Moving navbar is getting hidden behind content.

### Screenshots

<img width="550" alt="Screenshot 2024-10-17 at 8 12 08 PM" src="https://github.com/user-attachments/assets/9e163fd7-1b8f-448e-8bf9-d34c4a6c3b5f">
<img width="627" alt="Screenshot 2024-10-17 at 8 12 16 PM" src="https://github.com/user-attachments/assets/51873546-57e1-404a-b509-a4979184adb8">

### What browser are you seeing the problem on?

Chrome

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/beRajeevKumar/Frontend_Mentor/blob/main/Code_Of_Conduct.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by ishivansmishra** [comment]
@beRajeevKumar please assign me this issue i will fixed it under label hacktoberfest and gssoc extended and level

**Comment by beRajeevKumar** [comment]
Go for it

**Comment by ishivansmishra** [comment]
@beRajeevKumar Please assign me
