### ISSUE TITLE
[BUG] Sign uppage

### ISSUE THREAD

**Issue by saumyayadav25** [beRajeevKumar/Frontend_Mentor#458]
### Description

Duplicate sign up page, not looking good. one of them must be removed. 
The one in first screenshot must be removed.

### Screenshots

<img width="1032" alt="Screenshot 2024-10-19 at 8 48 25 AM" src="https://github.com/user-attachments/assets/18c63a1d-cbd1-4989-a696-406b35306276">
<img width="1354" alt="Screenshot 2024-10-19 at 8 48 20 AM" src="https://github.com/user-attachments/assets/671d59f1-339d-445f-9ba1-143ef127cfba">

### What browser are you seeing the problem on?

Chrome

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/beRajeevKumar/Frontend_Mentor/blob/main/Code_Of_Conduct.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by Aditya90456** [comment]
i can make @saumyayadav25

**Comment by saumyayadav25** [comment]
@beRajeevKumar kindly review this issue.

**Comment by Aditya90456** [comment]
> @beRajeevKumar kindly review this issue.

ok

**Comment by Aditya90456** [comment]
i can make sure amazing ui @saumyayadav25
