### ISSUE TITLE
[Feat]Add Responsive E-Commerce Website

### ISSUE THREAD

**Issue by amanver45** [beRajeevKumar/Frontend_Mentor#465]
### Description

This feature aims to implement a fully responsive e-commerce website that provides a seamless shopping experience across various devices. The website will include essential functionalities such as product listings, a shopping cart, user authentication, and payment processing. Additionally, it will be designed with a mobile-first approach to ensure optimal performance on smartphones and tablets. The implementation will use modern frameworks and libraries to enhance user experience and maintain scalability.

### Screenshots

N/A

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/beRajeevKumar/Frontend_Mentor/blob/main/Code_Of_Conduct.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by gourabbistu089** [comment]
i want to implement this features
