### ISSUE TITLE
[Feat] Add About us page to link to the footer

### ISSUE THREAD

**Issue by Annapoornaaradhya** [beRajeevKumar/Frontend_Mentor#480]
### Description

There is About us n the footer but is not linked to any page I would like to add this feature.
@beRajeevKumar please assign me this issue under gssoc-ext level and hacktoberfest-accecpted tags

### Screenshots

![image](https://github.com/user-attachments/assets/7f42904e-a933-4ef1-97ce-35dcbd6879a0)
![image](https://github.com/user-attachments/assets/b7bf1be5-493d-4efb-87b8-9360387e7e14)

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/beRajeevKumar/Frontend_Mentor/blob/main/Code_Of_Conduct.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by Annapoornaaradhya** [comment]
@beRajeevKumar can you please review and accept the PR

**Comment by Pariyul** [comment]
hey do assign this to me

**Comment by Annapoornaaradhya** [comment]
> hey do assign this to me

I have already worked on this!!
