### ISSUE TITLE
Work on LOGO!

### ISSUE THREAD

**Issue by Ashmita-15** [beRajeevKumar/Frontend_Mentor#49]
The logo of the website is very simple. I can make some changes in it. Can you please give me one chance and assign this work to me:)
![Screenshot 2024-10-03 011304](https://github.com/user-attachments/assets/e1c11b30-b0b3-41d0-a96d-05b715dde8df)

**Comment by beRajeevKumar** [comment]
Here you go 🚀  and make changes.
