### ISSUE TITLE
[Feat]  Add Zomato Clone Feature to Project

### ISSUE THREAD

**Issue by Ankul8471** [beRajeevKumar/Frontend_Mentor#495]
### Description

This issue proposes adding a Zomato clone to our project. The feature should replicate essential functionalities of Zomato, including restaurant listings, search and filter options, user reviews, and location-based restaurant suggestions. The clone should be user-friendly, responsive, and scalable. It will use APIs for fetching restaurant data and will implement a clean UI for seamless user experience. This will provide a comprehensive demonstration of how a restaurant discovery app can be integrated into our existing project structure.

### Screenshots

![Screenshot 2024-10-20 225135](https://github.com/user-attachments/assets/2db979cb-49f8-4c64-928b-423e42dd9a65)

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/beRajeevKumar/Frontend_Mentor/blob/main/Code_Of_Conduct.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by Ankul8471** [comment]
@beRajeevKumar hello sir please assign me this.....

**Comment by beRajeevKumar** [comment]
go for it.
