### ISSUE TITLE
[Feat]   Add Swiggy Clone Feature to Project

### ISSUE THREAD

**Issue by Ankul8471** [beRajeevKumar/Frontend_Mentor#496]
### Description

This issue proposes adding a Swiggy clone to our project. The feature will replicate key functionalities of Swiggy, including restaurant and menu listings, real-time search, filtering options, and user ratings. Additionally, it should offer a smooth food ordering flow, from selecting items to tracking delivery status. The clone will incorporate API integrations for restaurant and delivery data, ensuring scalability and responsiveness across devices. This addition will enhance our project by showcasing a full-fledged food delivery app experience.

### Screenshots

![Screenshot 2024-10-20 225135](https://github.com/user-attachments/assets/c2094d2d-320c-4c4c-9d4a-62467f576b66)

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/beRajeevKumar/Frontend_Mentor/blob/main/Code_Of_Conduct.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by Ankul8471** [comment]
@beRajeevKumar   please assign me this ......

**Comment by Ankul8471** [comment]
@beRajeevKumar please assign me this ...

**Comment by beRajeevKumar** [comment]
Also fix the Projects that are not appear in UI
