### ISSUE TITLE
adding a beautiful form component as one of the projects 

### ISSUE THREAD

**Issue by YooAshu** [beRajeevKumar/Frontend_Mentor#5]
adding a beautiful form component as one of the projects , i have seen there is no form in the projects a form is necessary as one of the projects in the project list, please assign me

**Comment by himanshu-sheetlani** [comment]
I want to contribute to this project as gssoc-ext contributor . please assign this issue to me.
I have made some beautiful forms earlier which i feel can help beginners.

**Comment by YooAshu** [comment]
@himanshu-sheetlani bro assign its been a week
