### ISSUE TITLE
Fix Bug in "11-order-summery-component" page.

### ISSUE THREAD

**Issue by beRajeevKumar** [beRajeevKumar/Frontend_Mentor#52]
The background image does not fit in the Big screen sizes.
Look here 👇
![Order Summery Project Bug](https://github.com/user-attachments/assets/b8824fbc-94d1-4a91-8e6e-6bb94d4a62cb)

**Comment by peterdanwan** [comment]
Hello @beRajeevKumar! I would be happy to try my shot at handling this issue. May I be assigned this issue for now?
