### ISSUE TITLE
Add Footer

### ISSUE THREAD

**Issue by shivamy009** [beRajeevKumar/Frontend_Mentor#6]
Add footer for more interactive

**Comment by himanshu-sheetlani** [comment]
I want to contribute to this project as gssoc-ext contributor . please assign this issue to me.
Please mention all the things that i should add in footer along with that please label this issue as gssoc or gssoc-ext.

**Comment by shivamy009** [comment]
I want to contribute to this project as gssoc-ext contributor . please assign this issue to me.
Please mention all the things that i should add in footer along with that please label this issue as gssoc or gssoc-ext.

**Comment by Prashant1659** [comment]
I want to contribute to this project. My experience with HTML, CSS and JavaScript will provide great assistance. Along with that i have knowledge of UI/UX.

**Comment by shivamy009** [comment]
I want to contribute to this project as gssoc-ext contributor . please assign this issue to me.
Please mention all the things that i should add in footer along with that please label this issue as gssoc or gssoc-ext.

**Comment by uzefaqureshi06** [comment]
can you assign this to me I will work on it I will make my best

**Comment by Bhavya445** [comment]
assign me this issue

**Comment by uzefaqureshi06** [comment]
can you plzzz assign i will do my best

**Comment by uzefaqureshi06** [comment]
@shivamy009  he can you please assign this issue to me I will make my best
