### ISSUE TITLE
[Feat]: Add Calculator Application 

### ISSUE THREAD

**Issue by kaiyumdev** [beRajeevKumar/Frontend_Mentor#650]
### Description

The Modern Calculator Application is a sleek and intuitive web-based calculator designed to perform basic arithmetic operations with ease. This project aims to provide users with a clean and user-friendly interface for performing calculations such as addition, subtraction, multiplication, and division. The application supports decimal operations and offers instant computation results, making it a handy tool for everyday calculations.

### Screenshots

![calculator](https://github.com/user-attachments/assets/e7c5d208-c0ad-426a-952d-08915dfb87ac)

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/beRajeevKumar/Frontend_Mentor/blob/main/Code_Of_Conduct.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by kaiyumdev** [comment]
@Bhum-ika Can you please assign me the issue under hacktoberfest & gssoc-ext.

**Comment by BhavikaPachauri** [comment]
assign me the task under GSSOC AND HACKTOBERFEST .
