### ISSUE TITLE
Add button and hover selector to each components.

### ISSUE THREAD

**Issue by ADITHICJ** [beRajeevKumar/Frontend_Mentor#7]
I would like to make it attractive by adding buttons and hover effect. Please assign this issue to me under gssoc'24 extended with label gssoc'24 and hacktoberfest.

**Comment by beRajeevKumar** [comment]
@ADITHICJ, Share what your design solution looks like. 
we are working on the design of the project, so join the Figma link here and make some of its design. Then code it.
Here is the Figma link: 
https://www.figma.com/design/Gpp9lztaz36xu9nuGt7FBE/Frontend-Mentor?node-id=0-1&t=vJh3LEbs3Fw4ZmwL-1
If you have any doubts, feel free to ask and resolve them sooner on the Discord server below. It's a good idea to communicate better.
https://discord.gg/eXrQqgRX

**Comment by ADITHICJ** [comment]
Here is my design : https://www.figma.com/proto/Gpp9lztaz36xu9nuGt7FBE/Frontend-Mentor?node-id=41-3&node-type=canvas&t=n8s9DIKTcJ1hEXP4-1&scaling=min-zoom&content-scaling=fixed&page-id=0%3A1
Is this good?
