### ISSUE TITLE
Incorrect Alignment of Underline in Projects

### ISSUE THREAD

**Issue by Vd7905** [beRajeevKumar/Frontend_Mentor#8]
<img width="915" alt="front end" src="https://github.com/user-attachments/assets/608165d8-963c-467d-ab9f-83f634846f37">
Incorrect Alignment of Underline in Projects this can be fixed.
@beRajeevKumar could you assign this to me i will fix this

**Comment by beRajeevKumar** [comment]
Yeah, I noticed this later, Thank you for the make my attention to that issue in the project.
Go for it 🚀

If you have any further doubts, then join the Discord server for better communication and resolving the doubts as soon as possible.
https://discord.gg/eXrQqgRX
