### ISSUE TITLE
Add NAVBAR!

### ISSUE THREAD

**Issue by Kevindua26** [beRajeevKumar/Frontend_Mentor#80]
### 404 no navbar found, **will add the NAVBAR to the website.**

For example (sample NAVBAR)
[https://kevindua26.github.io/EchoSync/](url)
![Screenshot 2024-10-04 003008](https://github.com/user-attachments/assets/c508163d-de27-4f79-9f14-1c2968c39dd0)

@KiranBaliga @beRajeevKumar @J-B-Mugundh @himanshu-sheetlani @Ashmita-15

**Comment by anubhab1001** [comment]
@beRajeevKumar I want to work on this issue. Please assign me .

**Comment by 8721111** [comment]
i also want to work this issue

**Comment by Supraja-Gao** [comment]
please assign this to me. I would like to work on this issue.

**Comment by KharjulSneha** [comment]
i would like to work on this issue. please assign me.
