### ISSUE TITLE
Missing Header, Logo, Nav Bar, Menu Bar and name of website

### ISSUE THREAD

**Issue by ParulPrashar** [beRajeevKumar/Frontend_Mentor#9]
There no navigation bar, logo and name of website which should be enhanced soon.
@beRajeevKumar Kindly assign this issue to me labels gssoc, hackoberfest

**Comment by Shiv13jm** [comment]
@beRajeevKumar  can you assign it to me ?

**Comment by akdwivedi-explorer** [comment]
@beRajeevKumar 
 Hi, I'm Ashutosh Dwivedi. I have experience in frontend development, specifically with React.js, Next.js, HTML, CSS, and JavaScript. I’m excited about contributing to open-source and would love to work on this project.

Could you please assign me an issue under Hacktoberfest? I'm looking forward to making meaningful contributions and learning from the community!

Thank you!

**Comment by ParulPrashar** [comment]
@beRajeevKumar Sir it is a request kindly assign the issue on 1st come 1st serve, as it takes a lot to find issues and start early

**Comment by rohitsharma2610** [comment]
can you please assign this issue to me, i want to work on it.

**Comment by moudgalya1223** [comment]
can you please assign this issue to me, i want to work on it.
