### ISSUE TITLE
Add Favicon to Website

### ISSUE THREAD

**Issue by anshika-verma05** [beRajeevKumar/Frontend_Mentor#91]
Feature Request: Add Favicon
It would be great to add a favicon to the website to enhance user experience and brand recognition. A favicon is the small icon that appears on the browser tab and bookmark bars, and it helps users identify and locate the site more easily.

![preview](https://github.com/user-attachments/assets/0c01af18-4de0-442f-91fe-ec1fd17696d5)
I would like to add this as a favicon for this website.

I would love to work on this project under the GSSoC Exd and Hacktoberfest initiatives. Please consider assigning this issue to me so I can contribute and help make this learning project available to the community.

**Comment by pameladeysarkar2003** [comment]
please assign me with the task @beRajeevKumar

**Comment by MohammadAhmadSiddiqui** [comment]
Hi @beRajeevKumar,


As I can see the favicon is not visible, would you like to assign me this issue?

Thank you!
Ahmad

**Comment by Abhijais4896** [comment]
Can i work on this issue, as favicon is not visible in website . please assign me to resolve this issue.
