### ISSUE TITLE
bug: cards overflow to the header when hover on any card and scroll.

### ISSUE THREAD

**Issue by ritikm31** [beRajeevKumar/Frontend_Mentor#99]
whenever we hover on any cards it overflows and on scrolling goes over the header while scrolling and hide the whole content that comes under it and overflow on the screen.

**Comment by vikas83pal** [comment]
Hello Please Could You Assign Me This Issue I want to work on this issue

**Comment by chetanck03** [comment]
hey assign me, i will solve this issue
